# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn CI & CD

on:
  # runs on all pull requests against main
  pull_request:
    branches: [ main ]
  # this is a reusable workflow that is called from the release workflow
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install production-level yarn dependencies
      uses: Borales/actions-yarn@v2.3.0
      with:
          cmd: install --frozen-lockfile --production
    - name: Build output for prod
      uses: Borales/actions-yarn@v2.3.0
      with:
          cmd: build

  # CD-specific job
  release:
    if: ${{ inputs.release }}
    needs: build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set variables for tag generation
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Generate release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: "build/*"
          # don't use {{ github.sha }} here since that's the full SHA
          tag: 1.0.0-${{ steps.vars.outputs.sha_short }}
          token: ${{ secrets.GITHUB_TOKEN }}
